# Example configuration for distributed average consensus
nodes:
  node1: [rpi0.local, 5001]
  node2: [Legion5-MK.local, 5002]
  node3: [Legion5-MK.local, 5003]
  node4: [Legion5-MK.local, 5004]
  node5: [Legion5-MK.local, 5005]

model:
  path: "config/model.pth"

test_data:
  path: "config/test_dataset.pth"
  index: 0