nodes:
  node0: [127.0.0.1, 5000]
  node1: [127.0.0.1, 5001]
  node2: [127.0.0.1, 5002]
  node3: [127.0.0.1, 5003]
  node4: [127.0.0.1, 5004]

model:
  path: "config/model.pth"

test_data:
  path: "config/test_dataset.pth"
  index: 0