# Example configuration for distributed average consensus
hosts:
  node1: 127.0.0.1
  node2: 127.0.0.1
  node3: 127.0.0.1
ports:
  node1: 5001
  node2: 5002
  node3: 5003
neighbors:
  node1: [node2, node3]
  node2: [node1, node3]
  node3: [node1, node2]
initial_values:
  node1: 10.0
  node2: 20.0
  node3: 30.0
